### ISSUE TITLE
WC 2.7 Compatibility

### ISSUE THREAD

**Issue by bekarice** [skyverge/woocommerce-extra-product-sorting-options#9]
### PR in #10

 - [x] **Misc** -- Drop support for WooCommerce 2.3

 - [x] **Misc** -- Add support for WooCommerce 2.7
   - ~~**Investigate** Whether featured sorting can [be maintained due to this PR](https://github.com/woocommerce/woocommerce/pull/12527), drop if not.~~ {BR} Not possible without doing multiple queries + a custom shop template to output both.

 - [x] Update tested up to / requires versions

 - [x] Update readme + changelog

**Comment by justinstern** [comment]
:open_file_folder:
